### ISSUE TITLE
collection queries should fail 

### ISSUE THREAD

**Issue by souenzzo** [ComputeSoftware/datomic-client-memdb#13]
When I run

```
(d/q {:query '[:find [(pull ?e [*]) ...]
               :in $
               :where
               [?e :db/ident]]
      :args  [db]})
```

it should throw something like:

```
#error{:cause "Only find-rel elements are allowed in client find-spec, see http://docs.datomic.com/query.html#grammar",
       :data {:cognitect.anomalies/category :cognitect.anomalies/incorrect,
              :cognitect.anomalies/message "Only find-rel elements are allowed in client find-spec, see http://docs.datomic.com/query.html#grammar",
              :dbs [{:database-id "6a32fd06-cfad-4a8c-998d-934fb909fda4", :t 7, :next-t 8, :history false}]},
       :via [{:type clojure.lang.ExceptionInfo,
              :message "Only find-rel elements are allowed in client find-spec, see http://docs.datomic.com/query.html#grammar",
              :data {:cognitect.anomalies/category :cognitect.anomalies/incorrect,
                     :cognitect.anomalies/message "Only find-rel elements are allowed in client find-spec, see http://docs.datomic.com/query.html#grammar",
                     :dbs [{:database-id "6a32fd06-cfad-4a8c-998d-934fb909fda4", :t 7, :next-t 8, :history false}]},
              :at [datomic.client.api.async$ares invokeStatic "async.clj" 56]}],

```

**Comment by kennyjwilli** [comment]
Short of parsing the query, I don't think there's an easy way to prevent this. Ideas are welcome. This caveat is noted [here](https://github.com/ComputeSoftware/datomic-client-memdb#caveats). I suggest running integration tests against Datomic Cloud to ensure failures like this are caught. Further, ensure you and your team only write queries that Datomic Cloud supports :smile:

**Comment by souenzzo** [comment]
I'm thinking about a PR with a not-so-smart function, some tests/examples, just to avoid some common/enumerated mistakes.

It can throw or at least warn.

https://github.com/ComputeSoftware/datomic-client-memdb/blob/master/src/compute/datomic_client_memdb/core.clj#L50

**Comment by madstap** [comment]
Would you accept a PR with something like this? Would have saved me more time than I'd like to admit at work today.
```clojure
(defn ->map-query [query]
  (if (map? query)
    query
    (->> query
         (partition-by keyword?)
         (partition 2)
         (map (partial mapv vec))
         (map #(update % 0 first))
         (into {}))))

(defn collection-query? [query]
  (let [{fnd :find} (->map-query query)]
    (or (and (= 2 (count fnd))
             (= '. (second fnd)))
        (and (vector? (first fnd))
             (= 2 (count (first fnd)))
             (= '... (second (first fnd)))))))

(comment

  (collection-query? '[:find ?e .
                       :where [?e :foo/bar] [?e :baz/quux]])

  (collection-query? '[:find [(pull ?e [*]) ...]
                       :where [?e :foo/bar] [?e :baz/quux]])

  )
```

**Comment by kennyjwilli** [comment]
@madstap Ouch, that's the worst. I wish Cloud would support those :find specs. I have grown so accustom to never using them at this point haha. It'd be even better if they released a real local development solution! Maybe someday. 

Sure, I think a PR like that would be helpful to folks. You should be able to use `datomic.query.support/parse-as` to parse the query.

**Comment by souenzzo** [comment]
Maybe we can implement it as opt-in like this
https://github.com/clojure/core.async/blob/master/src/main/clojure/clojure/core/async.clj#L118

`"compute.datomic-client-memdb.query-checking"`

**Comment by kennyjwilli** [comment]
@souenzzo Do you have a use case where you'd want this client to return a result that would fail when used with Datomic Cloud? We were thinking to enable this by default.

**Comment by souenzzo** [comment]
It's just a extra-care to not break ANY workflow. But once it is a "testing tool" and has no official releases, I dont think that is really important this extra-care.

**Comment by kennyjwilli** [comment]
Could you say that those workflows were already broken by using an unsupported Datomic Client feature? :wink:
