### ISSUE TITLE
Divergent behavior for nil query args

### ISSUE THREAD

**Issue by jonwalch** [ComputeSoftware/datomic-client-memdb#21]
Datomic cloud version:
```
  "group-cft-version":"616",
  "group-cloud-version":"8879",
```

Repro:
```
(let [db (d/db conn)
        attrs nil]
    (d/q
      {:query '[:find ?e
                :in $ ?attrs]
       :args  [db attrs]}))
```

`attrs` can also be absent from the `in` clause and it will throw this same error.

Stack trace:
```
Execution error (IllegalArgumentException) at datomic.client.impl.shared/eval42582$fn$G (shared.clj:219).
No implementation of method: :->query-arg of protocol: #'datomic.client.impl.shared/QueryArg found for class: nil
```

I didn't see this behavior locally, but saw it once I deployed my query to production.

**Comment by kennyjwilli** [comment]
Thanks for this! 

What do you mean by "deployed my query to production"? Are you running in an Ion? It seems strange that the behavior would differ locally from production.

**Comment by jonwalch** [comment]
Sorry for being unclear. I called a query that did something similar in production and it threw this error. The code being tested uses `datomic-client-memdb` (obviously 😄). My tests that call this code path worked fine locally, but then threw this error in production when using an actual datomic insance. I do not use Ions.

**Comment by kennyjwilli** [comment]
I still cannot reproduce this: 

```clojure
(require '[datomic.client.api :as d])
(d/q
    {:query '[:find ?e
              :in $ ?attrs]
     :args  [(d/db conn) nil]})
Execution error (ExceptionInfo) at datomic.client.api.async/ares (async.clj:58).
Query is referencing unbound variables: #{?e}
```

**Comment by jonwalch** [comment]
@kennyjwilli which version of Datomic Cloud are you running?

**Comment by kennyjwilli** [comment]
Datomic Cloud 616 and `com.datomic/client-cloud 0.8.81`.

**Comment by jonwalch** [comment]
I upgraded to `0.8.81` and now I'm also seeing this
```
Execution error (ExceptionInfo) at datomic.client.api.async/ares (async.clj:58).
Query is referencing unbound variables: #{?e}
```

**Comment by kennyjwilli** [comment]
Ok, glad we're on the same page now :) Is this still an issue?

**Comment by jonwalch** [comment]
I'm not having the issue with the minimal repro that I wrote. It's still not throwing for my actual query.

Here's the smallest thing I could come up with that doesn't throw.

```
(let [db (d/db conn)
      id 1 ;; db id referring to another entity
      attrs nil]
  (d/q
    {:query '[:find ?e
              :in $ ?id
              :where [?e :foo/ref-to-something-else ?id]]
     :args  [db id attrs]}))
```

**Comment by kennyjwilli** [comment]
Can you send a full repro of what you are doing? I am not seeing a difference in results.

Here is my test case: 

```clojure
(defn run-test-case!
  [conn]
  (d/transact conn {:tx-data [{:db/ident       :name
                               :db/cardinality :db.cardinality/one
                               :db/valueType   :db.type/string}
                              {:db/ident       :my-ref
                               :db/cardinality :db.cardinality/one
                               :db/valueType   :db.type/ref}]})
  (let [{:keys [tempids]} (d/transact conn {:tx-data [{:db/id "a"
                                                       :name  "a"}
                                                      {:my-ref "a"
                                                       :name   "b"}]})]
    (d/q
      {:query '[:find ?e
                :in $ ?id
                :where
                [?e :my-ref ?id]]
       :args  [(d/db conn) (tempids "a") nil]})))
``` 
When running with a memdb conn and a Datomic Cloud conn, I get a single result returned. No exceptions.

**Comment by jonwalch** [comment]
I'm wrong. It's simply a difference between `0.8.78` and `0.8.81`. I'll close this ticket. Thanks for your help! I'll just need to keep my datomic client up to date in the future.
