### ISSUE TITLE
Publish on Clojars

### ISSUE THREAD

**Issue by kyptin** [ComputeSoftware/datomic-client-memdb#3]
My project includes some inexperienced developers who use Windows. I just realized that [the Clojure CLI tools don't work on Windows](https://clojure.org/guides/getting_started#_installation_on_windows) (also see [the official Jira issue](https://dev.clojure.org/jira/browse/TDEPS-67)). Yes, the Windows users can install a Linux environment, but that turns out to be a significant obstacle for beginners.

If you pushed a versioned artifact to Clojars or Maven, Leiningen (which works on Windows) could fetch the artifact. It looks like the standard way to push to Clojars these days is to use a tool like [depstar](https://github.com/healthfinch/depstar) or [cambada](https://github.com/luchiniatwork/cambada) to create a JAR, then use Maven [as described on the Clojars wiki](https://github.com/clojars/clojars-web/wiki/Pushing#maven) to push it to Clojars. (Also, Alex Miller mentioned in the `#tools-deps` channel of the Clojurians Slack that the `-Spom` option to `clojure`/`clj` will create (or update) a `pom.xml` file for you based on the contents of `deps.edn`.)

Let me know if this is something you're not interested in doing it, and I may just fork + push it myself.

**Comment by kennyjwilli** [comment]
I don't have the time to do this right now. Looks like juxt/pack has some instructions on [publishing an artifact to clojars](https://github.com/juxt/pack.alpha#uploading-to-clojars-or-maven). I'd be happy to accept a PR that automatically publishes an artifact to clojars when run on CI. Otherwise, I suggest the fork approach.

**Comment by kyptin** [comment]
Done. Fork is [here](https://github.com/clojars/clojars-web/wiki/Pushing#maven) and artifact is [here](https://clojars.org/datomic-client-memdb). Feel free to steal it back upstream; it's actually pretty straightforward.
