### ISSUE TITLE
Newest version not published to clojars

### ISSUE THREAD

**Issue by lennartbuit** [ComputeSoftware/datomic-client-memdb#8]
Hey there,

I noticed that @kyptin published this library to Clojars in ~October, however, the newer changes such as #7 are not included on Clojars.

Given that @kyptin is the one who published, should he update? Otherwise, would it be possible for you to publish a new version ^^?

**Comment by kennyjwilli** [comment]
@lennartbuit See my comment here: https://github.com/ComputeSoftware/datomic-client-memdb/issues/3#issuecomment-432769936. It's up to @kyptin if he wants to push a new update to his artifact.

**Comment by lennartbuit** [comment]
Yeah I figured, thats why I tagged him as well. Hope that it comes to his attention.

**Comment by lennartbuit** [comment]
I have deployed this lib to my companies private repository in the meanwhile. However, it would still be nice if the clojars version was updated for the next person to show up ^^.

**Comment by kyptin** [comment]
@lennartbuit [version 0.2.0](https://clojars.org/datomic-client-memdb/versions/0.2.0) with the latest code is now on Clojars. Cheers. :beer:

**Comment by lennartbuit** [comment]
Thank you 🥂!

**Comment by kennyjwilli** [comment]
@kyptin I have deployed the artifact to clojars under the group id computesoftware. If you give me access to `datomic-client-memdb`, I can take over from here.

**Comment by kyptin** [comment]
@kennyjwilli - Will do! What's your username on Clojars?

**Comment by kennyjwilli** [comment]
@kyptin kennyjwilli

**Comment by kyptin** [comment]
@kennyjwilli - Just added you as an admin on Clojars. Cheers!

**Comment by kennyjwilli** [comment]
Thanks @kyptin! And thank you for taking the time to deploy a version to clojars in the mean time. The latest version `1.0.0` is available in Clojars under the group `datomic-client-memdb` now. You can add it to your project with 
```clojure
;; deps.edn 
datomic-client-memdb {:mvn/version "1.0.0"}

;; Lein
[datomic-client-memdb "1.0.0"]
```
